image: "scorpil/rust:stable"

cache:
  paths:
  - apt-cache/
  - /root/.cargo/

stages:
  - install_dependencies
  - test

install_dependencies:apt:
  stage: install_dependencies
  script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -yqq
    - apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -yqq --no-install-recommends build-essential libssl-dev

test:cargo:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --verbose --jobs 1 --release # Don't paralize to make errors more readable
